/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.1 		*/
/*  Created On : 02-ago.-2021 1:01:34 p. m. 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS `parking` CASCADE
;

DROP TABLE IF EXISTS `parking_log` CASCADE
;

/* Create Tables */

CREATE TABLE `parking`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`code` VARCHAR(50) NOT NULL,
	`is_free` BOOL NOT NULL,
	`car_number` VARCHAR(50) NULL,
	`arrived` DATETIME NULL,
	CONSTRAINT `PK_parking` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `parking_log`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`code` VARCHAR(50) NOT NULL,
	`car_number` VARCHAR(50) NOT NULL,
	`arrived` DATETIME NOT NULL,
	`departure` DATETIME NOT NULL,
	`minutes` INT NOT NULL,
	`parking_i` INT NOT NULL,
	CONSTRAINT `PK_parking_log` PRIMARY KEY (`id` ASC)
)

;

SET FOREIGN_KEY_CHECKS=1
; 



INSERT INTO parking (code, is_free) VALUES ('L1', 1); 
INSERT INTO parking (code, is_free) VALUES ('L2', 1);
INSERT INTO parking (code, is_free) VALUES ('L3', 1);
INSERT INTO parking (code, is_free) VALUES ('L4', 1);
INSERT INTO parking (code, is_free) VALUES ('L5', 1);
INSERT INTO parking (code, is_free) VALUES ('R1', 1);
INSERT INTO parking (code, is_free) VALUES ('R2', 1);
INSERT INTO parking (code, is_free) VALUES ('R3', 1);
INSERT INTO parking (code, is_free) VALUES ('R4', 1);
INSERT INTO parking (code, is_free) VALUES ('R5', 0);