/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Classes.*;
import java.awt.HeadlessException;
import java.awt.event.WindowEvent;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.OK_CANCEL_OPTION;

/**
 *
 * @author maria
 */
public class TiqueteForm extends javax.swing.JFrame {
    LinkedList<Pasajero> kidsList = new LinkedList<>();
    LinkedList<PasajeroAdulto> adultosList = new LinkedList<>();
    TiqueteImprimir tiquete;
    
    /**
     * Creates new form TiqueteForm
     */
    public TiqueteForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        salidaLabel = new javax.swing.JLabel();
        txtSalida = new javax.swing.JTextField();
        txtLlegada = new javax.swing.JTextField();
        llegadaLabel = new javax.swing.JLabel();
        fechaLabel = new javax.swing.JLabel();
        txtFecha = new javax.swing.JFormattedTextField();
        horaLabel = new javax.swing.JLabel();
        cbHora = new javax.swing.JComboBox<>();
        horaLabel1 = new javax.swing.JLabel();
        cbMinutos = new javax.swing.JComboBox<>();
        adultosLabel = new javax.swing.JLabel();
        cbNumAdultos = new javax.swing.JComboBox<>();
        kidsLabel = new javax.swing.JLabel();
        cbNumKids = new javax.swing.JComboBox<>();
        adultosLabel1 = new javax.swing.JLabel();
        cbValortrayecto = new javax.swing.JComboBox<>();
        cbTipo = new javax.swing.JComboBox<>();
        kidsLabel1 = new javax.swing.JLabel();
        BtnComprar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Title.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Title.setText("Comprar Tiquetes");

        salidaLabel.setText("Ciudad de Salida: ");

        txtSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalidaActionPerformed(evt);
            }
        });

        txtLlegada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLlegadaActionPerformed(evt);
            }
        });

        llegadaLabel.setText("Ciudad de Llegada: ");

        fechaLabel.setText("Fecha de Salida:");

        txtFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        txtFecha.setToolTipText("dd/MM/yy");
        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });

        horaLabel.setText("Hora de Salida:");

        cbHora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22" }));
        cbHora.setToolTipText("");

        horaLabel1.setText("Minutos");

        cbMinutos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "05", "10", "15", "20", "25", "30", "35", "40", "45", "50", "55" }));
        cbMinutos.setToolTipText("");
        cbMinutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMinutosActionPerformed(evt);
            }
        });

        adultosLabel.setText("Pasajeros Adultos:");

        cbNumAdultos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        kidsLabel.setText("Pasajeros Niños:");

        cbNumKids.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));

        adultosLabel1.setText("Valor trayecto:");

        cbValortrayecto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "30000", "40000", "50000", "60000" }));

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Salida", "Salida y Regreso" }));

        kidsLabel1.setText("Tipo de Tiquete:");

        BtnComprar.setText("Comprar");
        BtnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnComprarActionPerformed(evt);
            }
        });

        btnImprimir.setText("Cerrar e Imprimir Tiquete");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(salidaLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(llegadaLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(fechaLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(adultosLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbNumAdultos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(adultosLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbValortrayecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(horaLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(horaLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(kidsLabel)
                                            .addComponent(kidsLabel1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbNumKids, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 40, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(BtnComprar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnImprimir)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salidaLabel)
                    .addComponent(txtSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(llegadaLabel)
                    .addComponent(txtLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaLabel)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horaLabel)
                    .addComponent(cbHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horaLabel1)
                    .addComponent(cbMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(adultosLabel)
                            .addComponent(cbNumAdultos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kidsLabel)
                            .addComponent(cbNumKids, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(adultosLabel1)
                            .addComponent(cbValortrayecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kidsLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(BtnComprar)
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnImprimir)
                        .addContainerGap())))
        );

        jTabbedPane2.addTab("Info Tiquetes", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbMinutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMinutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMinutosActionPerformed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    private void txtLlegadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLlegadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLlegadaActionPerformed

    private void txtSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalidaActionPerformed

    private void BtnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnComprarActionPerformed
        try{
            String salida = txtSalida.getText();
            String llegada = txtLlegada.getText();
            String fechaSalida = txtFecha.getText();
                        
            if(salida.equals("") || llegada.equals("") || fechaSalida.equals("")){
                JOptionPane.showMessageDialog(this, "Fill all fields");
            }else{
                for(int i = 0; i<Integer.parseInt(cbNumAdultos.getSelectedItem().toString()); i++){
                    PasajeroAdultoForm adulto = new PasajeroAdultoForm(("Pasajero Adulto"+i));
                    adulto.getFrame(adulto);
                    javax.swing.JLabel nombreLabel = new javax.swing.JLabel();
                    nombreLabel.setText("Nombre del Pasajero "+i+": ");
                    adultosList.add(adulto.getPasajero());
                }
                for(int i = 0; i<Integer.parseInt(cbNumKids.getSelectedItem().toString()); i++){
                    PasajeroKidForm kid = new PasajeroKidForm(("Pasajero Niño"+i));
                    kid.getFrame(kid);
                    kidsList.add(kid.getPasajero());
                }
                
                    
            }
        }catch(HeadlessException e){
            JOptionPane.showMessageDialog(this, "Error");
            System.out.println(e);
        }
        
    }//GEN-LAST:event_BtnComprarActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        try{
            String salida = txtSalida.getText();
            String llegada = txtLlegada.getText();
            String fechaSalida = txtFecha.getText();
            String horaSalida = cbHora.getSelectedItem().toString();
            String minutosSalida = cbMinutos.getSelectedItem().toString();
            int numPasajerosAdultos = Integer.parseInt(cbNumAdultos.getSelectedItem().toString());
            int numPasajerosKids = Integer.parseInt(cbNumKids.getSelectedItem().toString());
            int valorTrayecto = Integer.parseInt(cbValortrayecto.getSelectedItem().toString());
            String tipoTiquete = cbTipo.getSelectedItem().toString();
        
            
            if(salida.equals("") || llegada.equals("") || fechaSalida.equals("")){
                JOptionPane.showMessageDialog(this, "Fill all fields");
            }else{
                this.tiquete = new TiqueteImprimir(kidsList, adultosList, salida, llegada, fechaSalida, horaSalida, minutosSalida, numPasajerosAdultos, numPasajerosKids, valorTrayecto, tipoTiquete);
            }
        }catch(HeadlessException e){
            JOptionPane.showMessageDialog(this, "Error");
            System.out.println(e);
        }
        int resp = JOptionPane.showConfirmDialog(this, "Imprimiendo Tiquete", "ImprimirTiquete", OK_CANCEL_OPTION);
        if (resp==0){
            tiquete.imprimirTiquete(); this.dispose();
        }
    }//GEN-LAST:event_btnImprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TiqueteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TiqueteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TiqueteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TiqueteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TiqueteForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnComprar;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel adultosLabel;
    private javax.swing.JLabel adultosLabel1;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JComboBox<String> cbHora;
    private javax.swing.JComboBox<String> cbMinutos;
    private javax.swing.JComboBox<String> cbNumAdultos;
    private javax.swing.JComboBox<String> cbNumKids;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JComboBox<String> cbValortrayecto;
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JLabel horaLabel;
    private javax.swing.JLabel horaLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel kidsLabel;
    private javax.swing.JLabel kidsLabel1;
    private javax.swing.JLabel llegadaLabel;
    private javax.swing.JLabel salidaLabel;
    private javax.swing.JFormattedTextField txtFecha;
    private javax.swing.JTextField txtLlegada;
    private javax.swing.JTextField txtSalida;
    // End of variables declaration//GEN-END:variables
}
